version: "3"
tasks:
  default:
    silent: true
    cmds:
      - task --list-all
  migrate/local:
    silent: true
    dotenv: ["./env/dev.env"]
    cmds:
      - tern migrate --migrations ./data/migrations
      - sqlc generate
  bootstrap/local:
    silent: true
    desc: Create an admin user locally.
    dotenv: ["./env/dev.env"]
    cmd: mage bootstrap
  dev:
    silent: true
    desc: Run the API with the dev environment.
    dotenv: ["./env/dev.env"]
    cmd: go run ./api
  gen/bearer:
    silent: true
    desc: Create a bearer token to use for local testing.
    dotenv: ["./env/dev.env"]
    cmd: mage genbearer
