version: "3"
tasks:
  default:
    silent: true
    cmds:
      - task --list-all
  migrate/local:
    silent: true
    dotenv: ["./env/dev.env"]
    cmds:
      - tern migrate --migrations ./data/migrations
      - sqlc generate
  dev:
    silent: true
    dotenv: ["./env/dev.env"]
    cmds:
      - templ generate
      - tailwindcss -i ./in.css -o ./api/assets/styles.css -m
      - go run ./api
