// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package data

import (
	"context"
)

const accountGetByID = `-- name: AccountGetByID :one
SELECT id, email, is_admin FROM account WHERE id = $1
`

func (q *Queries) AccountGetByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, accountGetByID, id)
	var i Account
	err := row.Scan(&i.ID, &i.Email, &i.IsAdmin)
	return i, err
}
