// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chef.sql

package data

import (
	"context"
)

const chefProfileCreate = `-- name: ChefProfileCreate :exec
INSERT INTO chef (
    id,
    account_id,
    display_name,
    description
)
VALUES ($1, $2, $3, $4)
`

type ChefProfileCreateParams struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) ChefProfileCreate(ctx context.Context, arg ChefProfileCreateParams) error {
	_, err := q.db.Exec(ctx, chefProfileCreate,
		arg.ID,
		arg.AccountID,
		arg.DisplayName,
		arg.Description,
	)
	return err
}
