// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   string           `json:"id"`
	Email                string           `json:"email"`
	PhoneNumber          pgtype.Text      `json:"phone_number"`
	IsAdmin              bool             `json:"is_admin"`
	IsRoot               bool             `json:"is_root"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	LastActive           pgtype.Timestamp `json:"last_active"`
	FirstName            pgtype.Text      `json:"first_name"`
	LastName             pgtype.Text      `json:"last_name"`
	ChefStatus           string           `json:"chef_status"`
	Password             pgtype.Text      `json:"password"`
	Provider             pgtype.Text      `json:"provider"`
	ProviderToken        pgtype.Text      `json:"provider_token"`
	ProviderRefreshToken pgtype.Text      `json:"provider_refresh_token"`
	ProviderLastRefresh  pgtype.Timestamp `json:"provider_last_refresh"`
	Picture              pgtype.Text      `json:"picture"`
	Disabled             bool             `json:"disabled"`
	IsArchived           bool             `json:"is_archived"`
	ArchivedAt           pgtype.Timestamp `json:"archived_at"`
	ArchivedBy           pgtype.Text      `json:"archived_by"`
}

type Collection struct {
}

type FeaturedChef struct {
}

type Pocket struct {
	ID         string           `json:"id"`
	Name       string           `json:"name"`
	AccountID  string           `json:"account_id"`
	IsArchived bool             `json:"is_archived"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type PocketRecipe struct {
}

type Recipe struct {
	ID          string           `json:"id"`
	ChefID      string           `json:"chef_id"`
	CoverImgID  string           `json:"cover_img_id"`
	Content     []byte           `json:"content"`
	Tags        []string         `json:"tags"`
	IsPublished bool             `json:"is_published"`
	IsHidden    bool             `json:"is_hidden"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID            string           `json:"id"`
	TokenHash     string           `json:"token_hash"`
	AccountID     string           `json:"account_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ExpiresAt     pgtype.Timestamp `json:"expires_at"`
	Invalidated   bool             `json:"invalidated"`
	InvalidatedAt pgtype.Timestamp `json:"invalidated_at"`
	InvalidatedBy pgtype.Text      `json:"invalidated_by"`
}
