// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

type Account struct {
	ID      string `json:"id"`
	Email   string `json:"email"`
	IsAdmin bool   `json:"is_admin"`
}
